# Generated by Django 4.2.4 on 2024-05-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descroption',
            new_name='description',
        ),
    ]
