# Generated by Django 4.2.4 on 2024-05-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_descroption_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
