# Generated by Django 4.2.4 on 2024-04-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
