# Generated by Django 4.2.4 on 2024-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_rename_image_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
