# Generated by Django 4.2.4 on 2024-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_access',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
